#!/bin/bash

# macOS configuration

set -e

# Acquire sudo credentials for this session.
sudo -v

echo "Applying system settings"
sudo systemsetup -setremotelogin on &> /dev/null  # SSH
sudo systemsetup -setrestartfreeze on &> /dev/null

echo "Applying desktop settings"
osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/System/Library/Desktop Pictures/Solid Colors/Stone.png"'

echo "Applying input settings"
defaults write -g ApplePressAndHoldEnabled -bool false  # Use key repeat
defaults write -g InitialKeyRepeat -int 18  # Start repeating quicker
defaults write -g KeyRepeat -int 2  # Once active, repeat the key much faster (but not as HAM as 1)
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false  # No smart quotes
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false # No period when hitting the space bar twice

echo "Applying Finder settings"
defaults write com.apple.finder NewWindowTarget -string "PfDo"  # Default to Documents
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
defaults write com.apple.finder AppleShowAllFiles -bool true  # Hidden files
defaults write -g AppleShowAllExtensions -bool true
defaults write com.apple.finder ShowStatusBar -bool true
defaults write com.apple.finder QLEnableTextSelection -bool true  # Quick Look
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true  # Display full path
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"  # Current folder
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"  # Column view
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
chflags nohidden ~/Library

echo "Applying Dock settings"
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0  # Show immediately
defaults write com.apple.dock tilesize -int 60
defaults write com.apple.dock magnification -bool true
defaults write com.apple.dock largesize -int 100
defaults write com.apple.dock showhidden -bool true
defaults write com.apple.dock showrecents -bool false

echo "Log out and log back in to make all settings take effect"
